Add URL test for WarpStudio

diff --git a/.github/workflows/image.yml b/.github/workflows/image.yml
--- a/.github/workflows/image.yml
+++ b/.github/workflows/image.yml
@@ -60,6 +60,13 @@ jobs:
             exit 1
           fi
 
+          echo "Test WarpStudio"
+          res=$(curl -Is http://127.0.0.1:8081/ | head -1)
+          if [[ "${res}" != "HTTP/1.1 200 OK" ]]; then
+            echo "Failed to test WarpStudio URL"
+            exit 1
+          fi
+
       - name: Build the main image
         run: |
           docker buildx build \
